// Site text, English (the source for every translation). Keys start with "app.".
const app = {
  // Header, navigation and footer
  "app.skip": "Skip to content",
  "app.nav.sections": "Sections",
  "app.nav.main": "Main",
  "app.nav.languages": "Languages",
  "app.nav.review": "Review",
  "app.nav.translate": "Translate",
  "app.tab.learn": "Learn",
  "app.tab.review": "Review",
  "app.tab.translate": "Translate",
  "app.tab.profile": "Profile",
  "app.tab.due": "due",
  "app.speak.label": "I speak",
  "app.install": "Install app",
  "app.account.yours": "Your account",
  "app.account.signIn": "Sign in",
  "app.account.progress": "Progress",
  "app.stats.streak": { one: "{n}-day streak", other: "{n}-day streak" },
  "app.stats.points": { one: "{count} point", other: "{count} points" },
  "app.stats.goal": "Daily goal: {done} of {goal} points",
  "app.stats.due": { one: "{n} phrase to review", other: "{n} phrases to review" },
  "app.footer.about":
    "Feliglot is a Felicity project. Course phrases were written and checked by AI and are waiting on review by native speakers — if something sounds off, tell us.",
  "app.footer.privacy": "Privacy",
  "app.footer.terms": "Terms",

  // Home page
  "app.home.eyebrow": "Five minutes. A whole new world.",
  "app.home.title1": "Learn any language.",
  "app.home.title2": "From the one you speak.",
  "app.home.intro":
    "Short, joyful lessons that start from your language — not someone else's. Hear every phrase, say it out loud, and review it just before you'd forget.",
  "app.home.choose": "Choose a language",
  "app.home.translate": "Translate something",
  "app.home.stat.languages": "languages",
  "app.home.stat.pairs": "language pairs",
  "app.home.stat.free": "Free",
  "app.home.stat.everyone": "for everyone",
  "app.home.pick.eyebrow": "Start here",
  "app.home.pick.title": "What do you want to learn?",
  "app.home.pick.body": "Set “I speak” at the top and every meaning appears in your language. Switch courses any time.",
  "app.home.how.eyebrow": "Built for momentum",
  "app.home.how.title": "A little every day goes far.",
  "app.home.how.hear.title": "Hear it",
  "app.home.how.hear.body": "Every phrase spoken aloud, as often as you like.",
  "app.home.how.practise.title": "Practise it",
  "app.home.how.practise.body": "Flashcards, then a quiz: pick, type and say the answer.",
  "app.home.how.keep.title": "Keep it",
  "app.home.how.keep.body": "Points, a daily goal and a streak that fits your life.",
  "app.home.why.eyebrow": "Why Feliglot",
  "app.home.why.title": "Rarely found anywhere else.",
  "app.home.why.own.title": "Learn from your own language",
  "app.home.why.own.body": "Not just English: meanings appear in any of the {n} languages, so a Hindi speaker can learn Japanese in Hindi.",
  "app.home.why.speak.title": "Speak, don't just tap",
  "app.home.why.speak.body": "Say the phrase out loud and Feliglot listens — real pronunciation practice, right in your browser.",
  "app.home.why.remember.title": "Remember for good",
  "app.home.why.remember.body": "Phrases come back for review on a schedule, just before you'd forget them.",
  "app.home.why.content.title": "{phrases} phrases, {lessons} lessons",
  "app.home.why.content.body": "From hello and thank you to hotels, restaurants, health and making plans.",
  "app.home.cta.title": "Your first five minutes start now.",
  "app.home.cta.body": "Free, no sign-up needed. Create an account later to keep your progress on every device.",
  "app.home.cta.button": "Start learning",

  // Language list
  "app.languages.title": "All languages",
  "app.languages.intro": "{courses} courses, each with the same {phrases} everyday phrases in {lessons} short lessons.",
  "app.picker.find": "Find a language",
  "app.picker.placeholder": "Search — e.g. Japanese, Swahili, हिन्दी",
  "app.picker.region": "Region",
  "app.picker.allRegions": "All regions",
  "app.picker.found": { one: "{n} language found", other: "{n} languages found" },
  "app.picker.youSpeak": "You speak this",
  "app.picker.done": "{done} of {total} lessons done",
  "app.picker.start": "Start learning",
  "app.picker.none": "No course for that language yet — more are on the way.",
  "app.picker.seeAll": "See all {n} languages",
  "app.region.Europe": "Europe",
  "app.region.Middle East & North Africa": "Middle East & North Africa",
  "app.region.South Asia": "South Asia",
  "app.region.East Asia": "East Asia",
  "app.region.Southeast Asia": "Southeast Asia",
  "app.region.Sub-Saharan Africa": "Sub-Saharan Africa",
  "app.region.Central Asia & Caucasus": "Central Asia & Caucasus",
  "app.region.Constructed": "Constructed",

  // Course names that say which variety they teach
  "app.lang.ar": "Arabic (Standard)",
  "app.lang.ar-gulf": "Arabic (Gulf)",
  "app.lang.ar-eg": "Arabic (Egyptian)",
  "app.lang.pt": "Portuguese (Brazil)",
  "app.lang.zh": "Chinese (Mandarin)",
  "app.lang.yue": "Cantonese",
  "app.lang.fil": "Filipino (Tagalog)",

  // Course page
  "app.course.learning": "Learning",
  "app.course.intro": "{phrases} everyday phrases in {lessons} short lessons.",
  "app.course.romanized": "Every phrase is also written in Latin letters so you can read it from day one.",
  "app.tagline.ar": "The Arabic of news, books and signs — understood across the Arab world.",
  "app.tagline.ar-gulf": "The everyday Arabic you hear in Dubai, Abu Dhabi and across the Gulf.",
  "app.tagline.ar-eg": "The Arabic of Cairo — and of most Arabic films, series and songs.",

  // Offline page
  "app.offline.title": "You're offline",
  "app.offline.body": "Lessons you've opened before still work. Reconnect to open new ones.",
  "app.offline.button": "My languages",
} as const;

export default app;
